/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect } from 'react';
import { runPlanKeydownEffect } from './planViewKeydown';

// Global plan keydown shortcut effect extracted from usePlanView. Delegates to runPlanKeydownEffect;
// deps object + dep array moved verbatim, fed from a single deps object passed by the host.
export const usePlanKeydownEffect = (deps: any) => {
  const {
    confirmDeleteRef, selectedObjectIdsRef, planRef, isReadOnlyRef, selectedObjectIdRef, selectedLinkIdRef,
    selectedRoomIdRef, zoomRef, allTypesOpen, corridorModal, corridorConnectionModal, corridorDoorModal,
    corridorDoorLinkModal, roomDrawMode, corridorDrawMode, corridorDoorDraft, roomDoorDraft, linkFromId,
    roomCatalogOpen, scaleMode, wallDrawMode, measureMode, quoteMode, saveRevisionOpen,
    photoViewer, selectedRoomId, selectedRoomIds, selectedCorridorId, selectedCorridorDoor, selectedRoomDoorId,
    copySelection, requestPaste, handleEdit, openEditRoom, getRoomIdAt, resolveRoomAssignmentForObject,
    isDeskType, isRackLinkId, isUserType, isWallType, push, t,
    setLinkEditId, setContextMenu, setPendingType, setRoomDrawMode, setRoomsOpen, setNewRoomMenuOpen,
    setRoomCatalogOpen, setCorridorDrawMode, setAllTypesDefaultTab, setAllTypesOpen, runBlockingUiShortcut, runDrawingShortcut,
    runDraftCancelShortcut, runConfirmDeleteShortcut, runCtrlArrowQuoteShortcut, runRotateShortcut, runSaveShortcut, runScaleShortcut,
    runTextShortcut, runUndoRedoShortcut, runSelectAllShortcut, runEscapeSelectionShortcut, runArrowShortcut, runDeleteShortcut,
    addRevision, addLink, cancelScaleMode, clearSelection, convertMeasurementToQuotes, deleteLink,
    deleteObject, finishWallDraw, getPlanUnsavedChanges, getLatestRevisionCached, getQuoteOrientation, markTouched,
    moveObject, notifyNonPeopleRoomBlocked, performRedo, performUndo, postAuditEvent, resetTouched,
    setConfirmDeleteCorridorId, setCorridorDoorDraft, setCorridorModal, setCorridorConnectionModal, setCorridorDoorLinkModal, setCorridorDoorModal,
    setSelection, setSelectedCorridorId, setSelectedCorridorDoor, startQuote, startWallDraw, stopMeasure,
    stopQuote, showMeasureToast, getPlanSnapshot, updateFloorPlan, updateObject, updateRoom,
    updateQuoteLabelPos,
  } = deps;

  useEffect(() => runPlanKeydownEffect({
        confirmDeleteRef,
        selectedObjectIdsRef,
        planRef,
        isReadOnlyRef,
        selectedObjectIdRef,
        selectedLinkIdRef,
        selectedRoomIdRef,
        zoomRef,
        allTypesOpen,
        corridorModal,
        corridorConnectionModal,
        corridorDoorModal,
        corridorDoorLinkModal,
        roomDrawMode,
        corridorDrawMode,
        corridorDoorDraft,
        roomDoorDraft,
        linkFromId,
        roomCatalogOpen,
        scaleMode,
        wallDrawMode,
        measureMode,
        quoteMode,
        saveRevisionOpen,
        photoViewer,
        selectedRoomId,
        selectedRoomIds,
        selectedCorridorId,
        selectedCorridorDoor,
        selectedRoomDoorId,
        copySelection,
        requestPaste,
        handleEdit,
        openEditRoom,
        getRoomIdAt,
        resolveRoomAssignmentForObject,
        isDeskType,
        isRackLinkId,
        isUserType,
        isWallType,
        push,
        t,
        setLinkEditId,
        setContextMenu,
        setPendingType,
        setRoomDrawMode,
        setRoomsOpen,
        setNewRoomMenuOpen,
        setRoomCatalogOpen,
        setCorridorDrawMode,
        setAllTypesDefaultTab,
        setAllTypesOpen,
        runBlockingUiShortcut,
        runDrawingShortcut,
        runDraftCancelShortcut,
        runConfirmDeleteShortcut,
        runCtrlArrowQuoteShortcut,
        runRotateShortcut,
        runSaveShortcut,
        runScaleShortcut,
        runTextShortcut,
        runUndoRedoShortcut,
        runSelectAllShortcut,
        runEscapeSelectionShortcut,
        runArrowShortcut,
        runDeleteShortcut,
  }), [
      addRevision,
      addLink,
      allTypesOpen,
      cancelScaleMode,
      clearSelection,
      convertMeasurementToQuotes,
      copySelection,
      deleteLink,
      deleteObject,
      finishWallDraw,
      getPlanUnsavedChanges,
      getLatestRevisionCached,
      getQuoteOrientation,
      isDeskType,
      isWallType,
      linkFromId,
      markTouched,
      measureMode,
      moveObject,
      notifyNonPeopleRoomBlocked,
      performRedo,
      performUndo,
      postAuditEvent,
      push,
      quoteMode,
      requestPaste,
      resetTouched,
      runArrowShortcut,
      runConfirmDeleteShortcut,
      runBlockingUiShortcut,
      runCtrlArrowQuoteShortcut,
      runDrawingShortcut,
      runDraftCancelShortcut,
      runEscapeSelectionShortcut,
      runRotateShortcut,
      runSaveShortcut,
      runScaleShortcut,
      runSelectAllShortcut,
      runTextShortcut,
      runUndoRedoShortcut,
      corridorDoorDraft,
      roomDoorDraft,
      corridorDrawMode,
      corridorModal,
      corridorConnectionModal,
      corridorDoorModal,
      corridorDoorLinkModal,
      roomDrawMode,
      roomCatalogOpen,
      saveRevisionOpen,
      scaleMode,
      selectedCorridorId,
      selectedCorridorDoor,
      selectedRoomDoorId,
      selectedRoomId,
      selectedRoomIds,
      setConfirmDeleteCorridorId,
      setCorridorDoorDraft,
      setCorridorModal,
      setCorridorConnectionModal,
      setCorridorDoorLinkModal,
      setCorridorDoorModal,
      setContextMenu,
      setSelection,
      setSelectedCorridorId,
      setSelectedCorridorDoor,
      startQuote,
      startWallDraw,
      stopMeasure,
      stopQuote,
      showMeasureToast,
      t,
      getPlanSnapshot,
      resolveRoomAssignmentForObject,
      runDeleteShortcut,
      updateFloorPlan,
      updateObject,
      updateRoom,
      updateQuoteLabelPos,
      photoViewer,
  ]);
};
