import { Client, ObjectTypeDefinition, WifiAntennaModel } from './types';
import { asSecurityObjectTypes, SECURITY_LAYER_ID, SECURITY_TYPE_IDS } from './security';

export const SEED_CLIENT_ID = 'seed-client-acme';
export const SEED_SITE_ID = 'seed-site-wall-street-01';
export const SEED_PLAN_ID = 'seed-plan-floor-0';
export const SEED_PLAN_IMAGE_URL = '/seed/new-default-plan.png';
export const ALL_ITEMS_LAYER_ID = 'all-items';
export const ALL_ITEMS_LAYER_COLOR = '#e11d48';
export const WALL_LAYER_COLOR = '#fb923c';
export const WIFI_LAYER_COLOR = '#0ea5e9';
export const QUOTE_LAYER_COLOR = '#f97316';
export const DEFAULT_USER_TYPES = ['user', 'real_user', 'generic_user'];
export const DEFAULT_CCTV_TYPES = ['camera'];
export const DEFAULT_RACK_TYPES = ['rack'];
export const DEFAULT_WIFI_TYPES = ['wifi'];
export const DEFAULT_TEXT_TYPES = ['text', 'postit'];
export const DEFAULT_IMAGE_TYPES = ['image'];
export const DEFAULT_PHOTO_TYPES = ['photo'];
export const DEFAULT_SECURITY_TYPES = SECURITY_TYPE_IDS;
export const WIFI_STANDARD_OPTIONS = [
  { id: '802.11', it: 'WiFi 1 (802.11)', en: 'WiFi 1 (802.11)' },
  { id: '802.11b', it: 'WiFi 2 (802.11b)', en: 'WiFi 2 (802.11b)' },
  { id: '802.11a', it: 'WiFi 3 (802.11a)', en: 'WiFi 3 (802.11a)' },
  { id: '802.11n', it: 'WiFi 4 (802.11n)', en: 'WiFi 4 (802.11n)' },
  { id: '802.11ac', it: 'WiFi 5 (802.11ac)', en: 'WiFi 5 (802.11ac)' },
  { id: '802.11ax', it: 'WiFi 6 (802.11ax)', en: 'WiFi 6 (802.11ax)' },
  { id: '802.11ax-6ghz', it: 'WiFi 6E (802.11ax 6 GHz)', en: 'WiFi 6E (802.11ax 6 GHz)' },
  { id: '802.11be', it: 'WiFi 7 (802.11be)', en: 'WiFi 7 (802.11be)' }
];
export const WIFI_DEFAULT_STANDARD = '802.11ax';
export const WIFI_RANGE_SCALE_MAX = 20;
export const TEXT_FONT_OPTIONS = [
  { value: 'Arial, sans-serif', label: 'Arial' },
  { value: 'Helvetica, Arial, sans-serif', label: 'Helvetica' },
  { value: '"Trebuchet MS", Arial, sans-serif', label: 'Trebuchet' },
  { value: 'Verdana, Arial, sans-serif', label: 'Verdana' },
  { value: 'Georgia, "Times New Roman", serif', label: 'Georgia' },
  { value: '"Times New Roman", Georgia, serif', label: 'Times' },
  { value: '"Courier New", Courier, monospace', label: 'Courier' },
  { value: '"Dosis", "Trebuchet MS", sans-serif', label: 'Dosis' },
  { value: '"Jost", "Trebuchet MS", sans-serif', label: 'Jost' },
  { value: '"Poppins", "Trebuchet MS", sans-serif', label: 'Poppins' },
  { value: '"Montserrat", "Trebuchet MS", sans-serif', label: 'Montserrat' },
  { value: '"Lato", "Trebuchet MS", sans-serif', label: 'Lato' },
  { value: '"Open Sans", "Trebuchet MS", sans-serif', label: 'Open Sans' },
  { value: '"Roboto", "Trebuchet MS", sans-serif', label: 'Roboto' },
  { value: '"Raleway", "Trebuchet MS", sans-serif', label: 'Raleway' },
  { value: '"Oswald", "Trebuchet MS", sans-serif', label: 'Oswald' },
  { value: '"Nunito", "Trebuchet MS", sans-serif', label: 'Nunito' },
  { value: '"Source Sans 3", "Trebuchet MS", sans-serif', label: 'Source Sans 3' },
  { value: '"Work Sans", "Trebuchet MS", sans-serif', label: 'Work Sans' },
  { value: '"Fira Sans", "Trebuchet MS", sans-serif', label: 'Fira Sans' },
  { value: '"PT Sans", "Trebuchet MS", sans-serif', label: 'PT Sans' },
  { value: '"Quicksand", "Trebuchet MS", sans-serif', label: 'Quicksand' },
  { value: '"Manrope", "Trebuchet MS", sans-serif', label: 'Manrope' },
  { value: '"Merriweather", "Times New Roman", serif', label: 'Merriweather' },
  { value: '"Playfair Display", "Times New Roman", serif', label: 'Playfair Display' },
  { value: '"Inter", "Trebuchet MS", sans-serif', label: 'Inter' },
  { value: '"Ubuntu", "Trebuchet MS", sans-serif', label: 'Ubuntu' },
  { value: '"Archivo", "Trebuchet MS", sans-serif', label: 'Archivo' },
  { value: '"DM Sans", "Trebuchet MS", sans-serif', label: 'DM Sans' },
  { value: '"Inconsolata", "Courier New", monospace', label: 'Inconsolata' }
];
export const TEXT_COLOR_OPTIONS = [
  { value: '#111827', label: 'Slate' },
  { value: '#0f172a', label: 'Ink' },
  { value: '#1f2937', label: 'Graphite' },
  { value: '#0ea5e9', label: 'Sky' },
  { value: '#3b82f6', label: 'Blue' },
  { value: '#6366f1', label: 'Indigo' },
  { value: '#8b5cf6', label: 'Violet' },
  { value: '#a855f7', label: 'Purple' },
  { value: '#ec4899', label: 'Pink' },
  { value: '#f43f5e', label: 'Rose' },
  { value: '#ef4444', label: 'Red' },
  { value: '#f97316', label: 'Orange' },
  { value: '#eab308', label: 'Amber' },
  { value: '#22c55e', label: 'Green' },
  { value: '#14b8a6', label: 'Teal' },
  { value: '#6b7280', label: 'Gray' }
];
export const DEFAULT_WALL_TYPES = [
  'wall_concrete',
  'wall_drywall_standard',
  'wall_drywall',
  'wall_drywall_heavy',
  'wall_glass_standard',
  'wall_glass_thin',
  'wall_brick',
  'wall_metal',
  'wall_wood',
  'wall_door_wood',
  'wall_door_metal',
  'wall_door_glass',
  'wall_window_single',
  'wall_window_double',
  'wall_window_triple'
];
export const DEFAULT_DESK_TYPES = [
  'desk_round',
  'desk_square',
  'desk_rect',
  'desk_double',
  'desk_long',
  'desk_trap',
  'desk_l',
  'desk_l_rev'
];
export const DEFAULT_DEVICE_TYPES = [
  'badge_door',
  'badge_presence',
  'intercom',
  'video_intercom',
  'router',
  'switch',
  'ups',
  'printer',
  'scanner',
  'dect',
  'tv',
  'microphone',
  'phone',
  'desktop',
  'laptop'
];
export const WALL_TYPE_IDS = DEFAULT_WALL_TYPES;

const buildWifiModel = (
  brand: string,
  model: string,
  modelCode: string,
  standard: string,
  band24: boolean,
  band5: boolean,
  band6: boolean,
  coverageSqm: number
): WifiAntennaModel => ({
  id: `${brand}-${modelCode}`.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
  brand,
  model,
  modelCode,
  standard,
  band24,
  band5,
  band6,
  coverageSqm
});

export const DEFAULT_WIFI_ANTENNA_MODELS: WifiAntennaModel[] = [
  buildWifiModel('Ubiquiti', 'E7', 'E7', '802.11be', true, true, true, 185),
  buildWifiModel('Ubiquiti', 'E7 Campus', 'E7-Campus-US', '802.11be', true, true, true, 465),
  buildWifiModel('Ubiquiti', 'E7 Campus Indoor', 'E7-Campus-Indoor', '802.11be', true, true, true, 465),
  buildWifiModel('Ubiquiti', 'E7 Audience', 'E7-Audience-US', '802.11be', false, true, true, 465),
  buildWifiModel('Ubiquiti', 'E7 Audience Indoor', 'E7-Audience-Indoor', '802.11be', false, true, true, 465),
  buildWifiModel('Ubiquiti', 'U7 Pro XGS', 'U7-Pro-XGS', '802.11be', true, true, true, 160),
  buildWifiModel('Ubiquiti', 'U7 Pro Max', 'U7-Pro-Max', '802.11be', true, true, true, 160),
  buildWifiModel('Ubiquiti', 'U7 Pro XG', 'U7-Pro-XG', '802.11be', true, true, true, 140),
  buildWifiModel('Ubiquiti', 'U7 Pro', 'U7-Pro', '802.11be', true, true, true, 140),
  buildWifiModel('Ubiquiti', 'U7 Pro Wall', 'U7-Pro-Wall', '802.11be', true, true, true, 140),
  buildWifiModel('Ubiquiti', 'U7 Pro XG Wall', 'U7-Pro-XG-Wall', '802.11be', true, true, true, 140),
  buildWifiModel('Ubiquiti', 'U7 Pro Outdoor', 'U7-Pro-Outdoor-US', '802.11be', true, true, true, 465),
  buildWifiModel('Ubiquiti', 'U7 Long-Range', 'U7-LR', '802.11be', true, true, false, 160),
  buildWifiModel('Ubiquiti', 'U7 Lite', 'U7-Lite', '802.11be', true, true, false, 115),
  buildWifiModel('Ubiquiti', 'U7 In-Wall', 'U7-IW', '802.11be', true, true, false, 115),
  buildWifiModel('Ubiquiti', 'U7 Outdoor', 'U7-Outdoor', '802.11be', true, true, false, 465),
  buildWifiModel('Ubiquiti', 'U6 Enterprise', 'U6-Enterprise', '802.11ax-6ghz', true, true, true, 140),
  buildWifiModel('Ubiquiti', 'U6 Enterprise In-Wall', 'U6-Enterprise-IW', '802.11ax-6ghz', true, true, true, 115),
  buildWifiModel('Ubiquiti', 'U6 Long-Range', 'U6-LR', '802.11ax', true, true, false, 185),
  buildWifiModel('Ubiquiti', 'U6 Mesh Pro', 'U6-Mesh-Pro', '802.11ax', true, true, false, 185),
  buildWifiModel('Ubiquiti', 'U6 Pro', 'U6-Pro', '802.11ax', true, true, false, 140),
  buildWifiModel('Ubiquiti', 'U6+', 'U6-PLUS', '802.11ax', true, true, false, 140),
  buildWifiModel('Ubiquiti', 'U6 Mesh', 'U6-Mesh', '802.11ax', true, true, false, 140),
  buildWifiModel('Ubiquiti', 'U6 Lite', 'U6-Lite', '802.11ax', true, true, false, 115),
  buildWifiModel('Ubiquiti', 'U6 In-Wall', 'U6-IW', '802.11ax', true, true, false, 115),
  buildWifiModel('Ubiquiti', 'U6 Extender', 'U6-Extender-US', '802.11ax', true, true, false, 115),
  buildWifiModel('Ubiquiti', 'AC Long-Range', 'UAP-AC-LR', '802.11ac', true, true, false, 185),
  buildWifiModel('Ubiquiti', 'AC Mesh Pro', 'UAP-AC-M-PRO', '802.11ac', true, true, false, 185),
  buildWifiModel('Ubiquiti', 'AC Pro', 'UAP-AC-PRO', '802.11ac', true, true, false, 140),
  buildWifiModel('Ubiquiti', 'nanoHD', 'UAP-nanoHD', '802.11ac', true, true, false, 140),
  buildWifiModel('Ubiquiti', 'FlexHD', 'UAP-FlexHD', '802.11ac', true, true, false, 140),
  buildWifiModel('Ubiquiti', 'AC Mesh', 'UAP-AC-M', '802.11ac', true, true, false, 140),
  buildWifiModel('Ubiquiti', 'AC Lite', 'UAP-AC-LITE', '802.11ac', true, true, false, 115),
  buildWifiModel('Ubiquiti', 'Swiss Army Knife', 'UK-Ultra', '802.11ac', true, true, false, 115),
  buildWifiModel('Ubiquiti', 'In-Wall HD', 'UAP-IW-HD', '802.11ac', true, true, false, 90),
  buildWifiModel('Ubiquiti', 'AC In-Wall', 'UAP-AC-IW', '802.11ac', true, true, false, 25),
  buildWifiModel('TP-Link', 'Omada Ceiling Mount AP', 'EAP610', '802.11ax', true, true, false, 115),
  buildWifiModel('TP-Link', 'Omada Ceiling Mount AP', 'EAP650', '802.11ax', true, true, false, 140),
  buildWifiModel('TP-Link', 'Omada Indoor/Outdoor AP', 'EAP772-Outdoor', '802.11be', true, true, true, 300),
  buildWifiModel('Aruba (HPE)', 'Instant On AP22', 'R4W01A', '802.11ax', true, true, false, 140),
  buildWifiModel('Aruba (HPE)', 'Instant On AP25', 'R9B28A', '802.11ax', true, true, false, 185),
  buildWifiModel('Aruba (HPE)', 'AP-505', 'R2H28A', '802.11ax', true, true, false, 150),
  buildWifiModel('Cisco Meraki', 'MR36', 'MR36-HW', '802.11ax', true, true, false, 140),
  buildWifiModel('Cisco Meraki', 'MR46', 'MR46-HW', '802.11ax', true, true, false, 185),
  buildWifiModel('Cisco Meraki', 'MR57', 'MR57-HW', '802.11ax-6ghz', true, true, true, 230),
  buildWifiModel('Ruckus', 'R550', '9U1-R550', '802.11ax', true, true, false, 185),
  buildWifiModel('Ruckus', 'R650', '9U1-R650', '802.11ax', true, true, false, 230),
  buildWifiModel('Ruckus', 'R760', '9U1-R760', '802.11ax-6ghz', true, true, true, 300),
  buildWifiModel('Grandstream', 'GWN7660', 'GWN7660', '802.11ax', true, true, false, 175),
  buildWifiModel('Grandstream', 'GWN7664', 'GWN7664', '802.11ax-6ghz', true, true, true, 250),
  buildWifiModel('Cambium Networks', 'XV2-2', 'C000000L033A', '802.11ax', true, true, false, 140),
  buildWifiModel('Cambium Networks', 'XE3-4', 'C000000L043A', '802.11ax-6ghz', true, true, true, 250),
  buildWifiModel('MikroTik', 'cAP ax', 'cAPGi-5HaxD2HaxD', '802.11ax', true, true, false, 120),
  buildWifiModel('Zyxel', 'NWA210AX', 'NWA210AX', '802.11ax', true, true, false, 180),
  buildWifiModel('Extreme Networks', 'AP305C', 'AP305C-XN', '802.11ax', true, true, false, 150),
  buildWifiModel('Extreme Networks', 'AP310C', 'AP310C-XN', '802.11ax', true, true, false, 180),
  buildWifiModel('Extreme Networks', 'AP505C', 'AP505C-XN', '802.11ax-6ghz', true, true, true, 250),
  buildWifiModel('Juniper Mist', 'AP32', 'AP32-US', '802.11ax', true, true, false, 170),
  buildWifiModel('Juniper Mist', 'AP43', 'AP43-US', '802.11ax', true, true, false, 220),
  buildWifiModel('Juniper Mist', 'AP63', 'AP63-US', '802.11ax-6ghz', true, true, true, 300),
  buildWifiModel('Fortinet (FortiAP)', 'FortiAP U42', 'FAP-U42EUS', '802.11ax', true, true, false, 140),
  buildWifiModel('Fortinet (FortiAP)', 'FortiAP U52', 'FAP-U52EUS', '802.11ax', true, true, false, 180),
  buildWifiModel('Fortinet (FortiAP)', 'FortiAP U62E', 'FAP-U62E-US', '802.11ax-6ghz', true, true, true, 250),
  buildWifiModel('H3C', 'Magic R3500AX', 'R3500AX', '802.11ax', true, true, false, 160),
  buildWifiModel('H3C', 'Magic R5500AX', 'R5500AX', '802.11ax', true, true, false, 210),
  buildWifiModel('H3C', 'Magic R6500AXE', 'R6500AXE', '802.11ax-6ghz', true, true, true, 270),
  buildWifiModel('EnGenius', 'EWS377', 'EWS377', '802.11ax', true, true, false, 185),
  buildWifiModel('EnGenius', 'EWS357', 'EWS357', '802.11ax', true, true, false, 150),
  buildWifiModel('EnGenius', 'ECW336', 'ECW336', '802.11ax-6ghz', true, true, true, 260),
  buildWifiModel('TP-Link Tapo (Non-Omada)', 'Tapo C530', 'C530', '802.11ax', true, true, false, 120),
  buildWifiModel('D-Link', 'DAP-X2830', 'DAP-X2830', '802.11ax', true, true, false, 170),
  buildWifiModel('D-Link', 'DAP-X3850', 'DAP-X3850', '802.11ax', true, true, false, 220),
  buildWifiModel('Netgear Insight', 'WAX610', 'WAX610', '802.11ax', true, true, false, 170),
  buildWifiModel('Netgear Insight', 'WAX630', 'WAX630', '802.11ax', true, true, false, 210),
  buildWifiModel('Netgear Insight', 'WAX650E', 'WAX650E', '802.11ax-6ghz', true, true, true, 260),
  buildWifiModel('Linksys', 'LAPAC1200', 'LAPAC1200-EU', '802.11ac', true, true, false, 120),
  buildWifiModel('Linksys', 'LAPAC2600', 'LAPAC2600-EU', '802.11ac', true, true, false, 180),
  buildWifiModel('Linksys', 'LAPAC1750', 'LAPAC1750-EU', '802.11ac', true, true, false, 150),
  buildWifiModel('Huawei', 'AP7060DN', 'AP7060DN', '802.11ax', true, true, false, 160),
  buildWifiModel('Huawei', 'AP8050DN', 'AP8050DN', '802.11ax', true, true, false, 210),
  buildWifiModel('Huawei', 'AP8150DN', 'AP8150DN', '802.11ax', true, true, false, 250),
  buildWifiModel('Tenda', 'WA361E', 'WA361E', '802.11ax', true, true, false, 140),
  buildWifiModel('Tenda', 'O6 Pro', 'O6 Pro', '802.11ax', true, true, false, 180),
  buildWifiModel('Tenda', 'TEF-EAP130', 'EAP130', '802.11ax', true, true, false, 170),
  buildWifiModel('Huawei (Enterprise)', 'AP8050DE', 'AP8050DE', '802.11ax', true, true, false, 220),
  buildWifiModel('Dell EMC (Aruba OEM)', 'WAP371', 'WAP371', '802.11ac', true, true, false, 140),
  buildWifiModel('Dell EMC / Aruba OEM', 'WAP581', 'WAP581', '802.11ax', true, true, false, 200),
  buildWifiModel('Huawei Cloud/Managed', 'AP5150DN', 'AP5150DN', '802.11ax', true, true, false, 210),
  buildWifiModel('Colubris / HPE (ex)', 'AP510', 'AP510-X', '802.11ac', true, true, false, 160),
  buildWifiModel('Nexxt Solutions', 'WAP-AC2100', 'AC2100', '802.11ac', true, true, false, 130),
  buildWifiModel('Nexxt Solutions', 'WAP-AX1800', 'AX1800', '802.11ax', true, true, false, 150),
  buildWifiModel('Zyxel (Pro Wireless)', 'WAX650S', 'WAX650S', '802.11ax', true, true, false, 180),
  buildWifiModel('Zyxel (Pro)', 'WAX660E', 'WAX660E', '802.11ax-6ghz', true, true, true, 260),
  buildWifiModel('Sophos (AP)', 'APX-130', 'APX-130', '802.11ax', true, true, false, 150),
  buildWifiModel('Sophos (AP)', 'APX-230', 'APX-230', '802.11ax', true, true, false, 200),
  buildWifiModel('Sophos (AP)', 'APX-330E', 'APX-330E', '802.11ax-6ghz', true, true, true, 280),
  buildWifiModel('FortiAP (Fortinet)', 'FortiAP U42-E', 'FAP-U42E', '802.11ax', true, true, false, 140),
  buildWifiModel('FortiAP (Fortinet)', 'FortiAP U52-E', 'FAP-U52E', '802.11ax', true, true, false, 180),
  buildWifiModel('FortiAP (Fortinet)', 'FortiAP U62E', 'FAP-U62E', '802.11ax-6ghz', true, true, true, 260),
  buildWifiModel('Allied Telesis', 'AT-AR415XT', 'AR415XT', '802.11ax', true, true, false, 150),
  buildWifiModel('Allied Telesis', 'AT-AR610S', 'AR610S', '802.11ax', true, true, false, 200),
  buildWifiModel('Allied Telesis', 'AT-AR650S', 'AR650S', '802.11ax-6ghz', true, true, true, 280),
  buildWifiModel('Samsung (Enterprise)', 'WEA500', 'WEA500', '802.11ac', true, true, false, 160),
  buildWifiModel('Samsung (Enterprise)', 'WEA550', 'WEA550', '802.11ax', true, true, false, 200),
  buildWifiModel('Edgecore (DZS)', 'WAP-AC1750', 'WAP-AC1750', '802.11ac', true, true, false, 170),
  buildWifiModel('Edgecore (DZS)', 'WAP-AX1800', 'WAP-AX1800', '802.11ax', true, true, false, 180),
  buildWifiModel('Edgecore (DZS)', 'WAP-AX3600', 'WAP-AX3600', '802.11ax', true, true, false, 220),
  buildWifiModel('Huawei CloudManaged', 'AP7100DN', 'AP7100DN', '802.11ax', true, true, false, 150),
  buildWifiModel('Huawei CloudManaged', 'AP9000DN', 'AP9000DN', '802.11ax', true, true, false, 220),
  buildWifiModel('Alcad', 'Air-420', 'AIR-420', '802.11ax', true, true, false, 130),
  buildWifiModel('Alcad', 'Air-600', 'AIR-600', '802.11ax', true, true, false, 170),
  buildWifiModel('Alcad', 'Air-600E', 'AIR-600E', '802.11ax-6ghz', true, true, true, 240),
  buildWifiModel('TP-Link (Deco Business)', 'EAP650', 'Deco EAP650', '802.11ax', true, true, false, 180),
  buildWifiModel('Mercusys', 'MAP-AX1800', 'MAP-AX1800', '802.11ax', true, true, false, 150),
  buildWifiModel('Mercusys', 'MAP-AX3000', 'MAP-AX3000', '802.11ax', true, true, false, 210),
  buildWifiModel('Mercusys', 'MAP-AX4200', 'MAP-AX4200', '802.11ax', true, true, false, 240),
  buildWifiModel('TP-Link (Rivaltà)', 'RE650', 'RE650', '802.11ac', true, true, false, 140),
  buildWifiModel('Belkin Business', 'BWA020', 'BWA020', '802.11ac', true, true, false, 130),
  buildWifiModel('Belkin Business', 'BWA040', 'BWA040', '802.11ax', true, true, false, 170),
  buildWifiModel('Belkin Business', 'BWA060E', 'BWA060E', '802.11ax-6ghz', true, true, true, 250),
  buildWifiModel('Lakota Networks', 'AX-2200', 'AX-2200', '802.11ax', true, true, false, 160),
  buildWifiModel('Lakota Networks', 'AX-3000', 'AX-3000', '802.11ax', true, true, false, 210),
  buildWifiModel('Lakota Networks', 'AX-5000E', 'AX-5000E', '802.11ax-6ghz', true, true, true, 260),
  buildWifiModel('Intelbras', 'IAP-1130', 'IAP-1130', '802.11ac', true, true, false, 150),
  buildWifiModel('Intelbras', 'IAP-1210', 'IAP-1210', '802.11ax', true, true, false, 200),
  buildWifiModel('Mercusys', 'MAP-AX6000', 'MAP-AX6000', '802.11ax', true, true, false, 250),
  buildWifiModel('Mercusys', 'MAP-AC2200', 'MAP-AC2200', '802.11ac', true, true, false, 180),
  buildWifiModel('LigoWave', 'NFT-2ac', 'NFT-2ac', '802.11ac', true, true, false, 200),
  buildWifiModel('LigoWave', 'LigoDLB 5', 'LIGO-DLB-5', '802.11ac', false, true, false, 250),
  buildWifiModel('LigoWave', 'LigoDLB 5-n', 'LIGO-DLB5-n', '802.11ac', true, true, false, 130),
  buildWifiModel('MikroTik', 'wAP R', 'RBwAPR-2nD-AM', '802.11n', true, true, false, 90),
  buildWifiModel('MikroTik', 'GrooveA-52HPn', 'RBGrooveA-52HPn', '802.11ac', false, true, false, 180),
  buildWifiModel('MikroTik', 'Audience', 'RBD25G-5HPacQD2HPnD', '802.11ac', true, true, false, 220),
  buildWifiModel('MikroTik', 'Audience 10s', 'RBD25G-10PacQD-Ax', '802.11ax', true, true, false, 260),
  buildWifiModel('OpenMesh', 'A60', 'OpenMesh A60', '802.11ax', true, true, false, 180),
  buildWifiModel('OpenMesh', 'A100', 'OpenMesh A100', '802.11ax', true, true, false, 230),
  buildWifiModel('Peplink', 'AP One AX', 'AP One AX', '802.11ax', true, true, false, 200),
  buildWifiModel('Peplink', 'AP Pro', 'AP Pro', '802.11ac', true, true, false, 180),
  buildWifiModel('Peplink', 'AP One 200', 'AP One 200', '802.11ac', true, true, false, 210),
  buildWifiModel('RFS (Radio Frequency Systems)', 'RFS-WL-AP-6E', 'RFSWLAP6E', '802.11ax-6ghz', true, true, true, 280),
  buildWifiModel('RFS', 'RFS-WL-AP-AX', 'RFSWLAPAX', '802.11ax', true, true, false, 220),
  buildWifiModel('Sophos', 'APX-110E', 'APX-110E', '802.11ax', true, true, false, 150),
  buildWifiModel('Sophos', 'APX-610', 'APX-610', '802.11ax', true, true, false, 210),
  buildWifiModel('Sophos', 'APX-630E', 'APX-630E', '802.11ax-6ghz', true, true, true, 260),
  buildWifiModel('Zebra (Motorola)', 'WAP6xxx', 'Series WAP6', '802.11ax', true, true, false, 160),
  buildWifiModel('Zebra', 'WAP7xxx', 'Series WAP7', '802.11ax', true, true, false, 200),
  buildWifiModel('Zebra', 'WAP6EXX', 'Series WAP6E', '802.11ax-6ghz', true, true, true, 280),
  buildWifiModel('TP-Link (Tapo Business)', 'EAP610-2', 'EAP610-2', '802.11ax', true, true, false, 150),
  buildWifiModel('Linksys Pro', 'LAP-EQ1750', 'LAPEQ1750', '802.11ac', true, true, false, 170),
  buildWifiModel('Linksys Pro', 'LAP-AX1800', 'LAPAX1800', '802.11ax', true, true, false, 200),
  buildWifiModel('ASUS (Business APC)', 'BRT-AC828', 'BRT-AC828', '802.11ac', true, true, false, 180),
  buildWifiModel('ASUS (Business APC)', 'BRT-AX88', 'BRT-AX88', '802.11ax', true, true, false, 230),
  buildWifiModel('ASUS (Business APC)', 'BRT-AXE5400', 'BRT-AXE5400', '802.11ax-6ghz', true, true, true, 260)
];

export const defaultData = (): Client[] => {
  return [
    {
      id: SEED_CLIENT_ID,
      name: 'ACME Inc.',
      shortName: 'ACME',
      address: 'Wall Street 01',
      description: 'Seed workspace',
      logoUrl: undefined,
      wifiAntennaModels: DEFAULT_WIFI_ANTENNA_MODELS,
      layers: [
        { id: ALL_ITEMS_LAYER_ID, name: { it: 'Tutti gli elementi', en: 'All Items' }, color: ALL_ITEMS_LAYER_COLOR, order: 1 },
        { id: 'users', name: { it: 'Utenti', en: 'Users' }, color: '#2563eb', order: 2, typeIds: DEFAULT_USER_TYPES },
        { id: 'devices', name: { it: 'Dispositivi', en: 'Devices' }, color: '#0ea5e9', order: 3, typeIds: DEFAULT_DEVICE_TYPES },
        { id: 'wifi', name: { it: 'WiFi', en: 'WiFi' }, color: WIFI_LAYER_COLOR, order: 4, typeIds: DEFAULT_WIFI_TYPES },
        { id: 'cctv', name: { it: 'CCTV', en: 'CCTV' }, color: '#22c55e', order: 5, typeIds: DEFAULT_CCTV_TYPES },
        { id: 'desks', name: { it: 'Scrivanie', en: 'Desks' }, color: '#8b5cf6', order: 6, typeIds: DEFAULT_DESK_TYPES },
        { id: SECURITY_LAYER_ID, name: { it: 'Sicurezza', en: 'Safety' }, color: '#ef4444', order: 7, typeIds: DEFAULT_SECURITY_TYPES },
        { id: 'cabling', name: { it: 'Cablaggi', en: 'Cabling' }, color: '#10b981', order: 8 },
        { id: 'walls', name: { it: 'Mura', en: 'Walls' }, color: WALL_LAYER_COLOR, order: 9, typeIds: DEFAULT_WALL_TYPES },
        { id: 'quotes', name: { it: 'Quote', en: 'Quotes' }, color: QUOTE_LAYER_COLOR, order: 10 },
        { id: 'rooms', name: { it: 'Stanze', en: 'Rooms' }, color: '#64748b', order: 11 },
        { id: 'corridors', name: { it: 'Corridoi', en: 'Corridors' }, color: '#94a3b8', order: 12 },
        { id: 'racks', name: { it: 'Rack', en: 'Racks' }, color: '#f97316', order: 13, typeIds: DEFAULT_RACK_TYPES },
        { id: 'text', name: { it: 'Testo', en: 'Text' }, color: '#0f172a', order: 14, typeIds: DEFAULT_TEXT_TYPES },
        { id: 'images', name: { it: 'Immagini', en: 'Images' }, color: '#64748b', order: 15, typeIds: DEFAULT_IMAGE_TYPES },
        { id: 'photos', name: { it: 'Foto', en: 'Photos' }, color: '#14b8a6', order: 16, typeIds: DEFAULT_PHOTO_TYPES }
      ],
      sites: [
        {
          id: SEED_SITE_ID,
          clientId: SEED_CLIENT_ID,
          name: 'Wall Street 01',
          floorPlans: [
            {
              id: SEED_PLAN_ID,
              siteId: SEED_SITE_ID,
              name: 'Floor 0',
              imageUrl: SEED_PLAN_IMAGE_URL,
              width: 650,
              height: 477,
              views: [
                {
                  id: 'seed-view-default',
                  name: 'DEFAULT',
                  zoom: 1.6,
                  pan: { x: 80, y: 20 },
                  isDefault: true
                }
              ],
              rooms: [],
              corridors: [],
              revisions: [],
              links: [],
              racks: [],
              rackItems: [],
              rackLinks: [],
              objects: []
            }
          ]
        }
      ]
    }
  ];
};

export const defaultObjectTypes: ObjectTypeDefinition[] = [
  { id: 'user', name: { it: 'Utente generico', en: 'Generic user' }, icon: 'user', builtin: true },
  { id: 'real_user', name: { it: 'Utente reale', en: 'Real user' }, icon: 'userCheck', builtin: true },
  { id: 'camera', name: { it: 'Telecamera', en: 'Camera' }, icon: 'camera', builtin: true },
  { id: 'badge_door', name: { it: 'Apriporta con badge', en: 'Badge door' }, icon: 'lockKeyhole', builtin: true },
  { id: 'badge_presence', name: { it: 'Marcatore presenze badge', en: 'Badge attendance marker' }, icon: 'badgeCheck', builtin: true },
  { id: 'intercom', name: { it: 'Citofono', en: 'Intercom' }, icon: 'intercom', builtin: true },
  { id: 'video_intercom', name: { it: 'Videocitofono', en: 'Video intercom' }, icon: 'videoIntercom', builtin: true },
  { id: 'rack', name: { it: 'Rack rete', en: 'Network rack' }, icon: 'server', builtin: true },
  { id: 'router', name: { it: 'Router', en: 'Router' }, icon: 'router', builtin: true },
  { id: 'switch', name: { it: 'Switch', en: 'Switch' }, icon: 'switch', builtin: true },
  { id: 'ups', name: { it: 'UPS', en: 'UPS' }, icon: 'battery', builtin: true },
  { id: 'printer', name: { it: 'Stampante', en: 'Printer' }, icon: 'printer', builtin: true },
  { id: 'scanner', name: { it: 'Scanner', en: 'Scanner' }, icon: 'scanner', builtin: true },
  { id: 'dect', name: { it: 'Antenna DECT', en: 'DECT antenna' }, icon: 'radio', builtin: true },
  { id: 'tv', name: { it: 'Televisore', en: 'TV' }, icon: 'tv', builtin: true },
  { id: 'microphone', name: { it: 'Microfono', en: 'Microphone' }, icon: 'mic', builtin: true },
  { id: 'phone', name: { it: 'Telefono', en: 'Phone' }, icon: 'phone', builtin: true },
  { id: 'desk_round', name: { it: 'Scrivania tonda', en: 'Round desk' }, icon: 'deskRound', builtin: true },
  { id: 'desk_square', name: { it: 'Scrivania quadrata', en: 'Square desk' }, icon: 'deskSquare', builtin: true },
  { id: 'desk_rect', name: { it: 'Scrivania rettangolare', en: 'Rectangular desk' }, icon: 'deskRect', builtin: true },
  { id: 'desk_double', name: { it: 'Scrivania doppia', en: 'Double desk' }, icon: 'deskDouble', builtin: true },
  { id: 'desk_long', name: { it: 'Banco lungo', en: 'Long bench' }, icon: 'deskLong', builtin: true },
  { id: 'desk_trap', name: { it: 'Scrivania trapezoidale', en: 'Trapezoid desk' }, icon: 'deskTrapezoid', builtin: true },
  { id: 'desk_l', name: { it: 'Scrivania a L', en: 'L-shaped desk' }, icon: 'deskL', builtin: true },
  { id: 'desk_l_rev', name: { it: 'Scrivania a L rovesciata', en: 'Reverse L desk' }, icon: 'deskLReverse', builtin: true },
  { id: 'door_standard', name: { it: 'Porta standard', en: 'Standard door' }, icon: 'lock', builtin: true, category: 'door', doorConfig: { isEmergency: false, trackVerification: false, remoteOpen: false } },
  { id: 'door_emergency', name: { it: 'Porta emergenza', en: 'Emergency door' }, icon: 'shieldAlert', builtin: true, category: 'door', doorConfig: { isEmergency: true, trackVerification: true, remoteOpen: false } },
  { id: 'door_remote', name: { it: 'Porta remota', en: 'Remote door' }, icon: 'unlock', builtin: true, category: 'door', doorConfig: { isEmergency: false, trackVerification: true, remoteOpen: true } },
  ...asSecurityObjectTypes(),
  // Keep legacy/common types for backward compatibility with existing workspaces
  { id: 'wifi', name: { it: 'Antenna Wi‑Fi', en: 'Wi‑Fi antenna' }, icon: 'wifi', builtin: true },
  { id: 'desktop', name: { it: 'PC fisso', en: 'Desktop PC' }, icon: 'desktop', builtin: true },
  { id: 'laptop', name: { it: 'Portatile', en: 'Laptop' }, icon: 'laptop', builtin: true },
  { id: 'text', name: { it: 'Testo', en: 'Text' }, icon: 'text', builtin: true },
  { id: 'image', name: { it: 'Immagine', en: 'Image' }, icon: 'image', builtin: true },
  { id: 'photo', name: { it: 'Foto', en: 'Photo' }, icon: 'image', builtin: true },
  { id: 'postit', name: { it: 'Post-it', en: 'Post-it' }, icon: 'postit', builtin: true },
  { id: 'wall_concrete', name: { it: 'Cemento', en: 'Concrete' }, icon: 'wall', builtin: true, attenuationDb: 15, category: 'wall' },
  { id: 'wall_drywall_standard', name: { it: 'Cartongesso (Standard)', en: 'Drywall (Standard)' }, icon: 'wall', builtin: true, attenuationDb: 3, category: 'wall' },
  { id: 'wall_drywall', name: { it: 'Cartongesso', en: 'Drywall' }, icon: 'wall', builtin: true, attenuationDb: 4, category: 'wall' },
  { id: 'wall_drywall_heavy', name: { it: 'Cartongesso (Rinforzato)', en: 'Drywall (Heavy Duty)' }, icon: 'wall', builtin: true, attenuationDb: 4, category: 'wall' },
  { id: 'wall_glass_standard', name: { it: 'Vetro (Standard)', en: 'Glass (Standard)' }, icon: 'wall', builtin: true, attenuationDb: 2, category: 'wall' },
  { id: 'wall_glass_thin', name: { it: 'Vetro (Sottile)', en: 'Glass (Thin)' }, icon: 'wall', builtin: true, attenuationDb: 1, category: 'wall' },
  { id: 'wall_brick', name: { it: 'Mattoni', en: 'Brick' }, icon: 'wall', builtin: true, attenuationDb: 5, category: 'wall' },
  { id: 'wall_metal', name: { it: 'Metallo', en: 'Metal' }, icon: 'wall', builtin: true, attenuationDb: 10, category: 'wall' },
  { id: 'wall_wood', name: { it: 'Legno', en: 'Wood' }, icon: 'wall', builtin: true, attenuationDb: 5, category: 'wall' },
  { id: 'wall_door_wood', name: { it: 'Porta (Legno)', en: 'Door (Wood)' }, icon: 'wall', builtin: true, attenuationDb: 5, category: 'wall' },
  { id: 'wall_door_metal', name: { it: 'Porta (Metallo)', en: 'Door (Metal)' }, icon: 'wall', builtin: true, attenuationDb: 10, category: 'wall' },
  { id: 'wall_door_glass', name: { it: 'Porta (Vetro)', en: 'Door (Glass)' }, icon: 'wall', builtin: true, attenuationDb: 2, category: 'wall' },
  { id: 'wall_window_single', name: { it: 'Finestra (Vetro singolo)', en: 'Window (Single Pane)' }, icon: 'wall', builtin: true, attenuationDb: 4, category: 'wall' },
  { id: 'wall_window_double', name: { it: 'Finestra (Doppio vetro)', en: 'Window (Double Pane)' }, icon: 'wall', builtin: true, attenuationDb: 7, category: 'wall' },
  { id: 'wall_window_triple', name: { it: 'Finestra (Triplo vetro)', en: 'Window (Triple Pane)' }, icon: 'wall', builtin: true, attenuationDb: 10, category: 'wall' }
];
